services:
  postgres:
    container_name: mastercode-db
    image: postgres:13.5
    restart: always
    env_file:
      - docker.env
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - postgres

  postgres-test:
    container_name: mastercode-db-test
    image: postgres:13.5
    restart: always
    env_file:
      - docker.env
    volumes:
      - postgres:/var/lib/postgresql/data-test
    ports:
      - '5439:5432'
    networks:
      - postgres

  cache:
    container_name: mastercode-redis-cache
    image: redis
    ports:
      - '6379:6379'
    restart: always
    volumes:
      - redis:/var/lib/redis-cache/mastercode-cache
    networks:
      - redis

volumes:
  postgres:
  redis:

networks:
  postgres:
    driver: bridge
  redis:
    driver: bridge
