services:
  postgres:
    container_name: mastercode-db
    image: postgres:13.5
    restart: always
    env_file:
      - docker.env
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - postgres

volumes:
  postgres:

networks:
  postgres:
    driver: bridge
